name: Hassfest

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  hassfest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run Hassfest
        uses: home-assistant/actions/hassfest@master
